domain: munaalfadl.com
url: https://munaalfadl.com
baseurl: "/"
title: "muna al fadl"
collections:
  works:
    output: true
    permalink: /works/:path
    order:
      - 2025/googleearth325917n363529e.md 
      - 2025/googleearth333042n361826e.md
      - 2025/googleearth333043n361823e.md
      - 2025/googleearth333102n361609e-closeup.md
      - 2025/googleearth333102n361609e.md
      - 2025/googleearth335112n363037e.md
      - 2025/damascus-souq-chair.md
      - 2025/aleppo-citadel.md
      - 2025/listening-to-the-news.md 
      - 2025/mosque.md 
      - 2024/looking-at-the-aleppo-citadel.md 
      - 2024/the-confrontation.md
      - 2024/looking-through-a-window.md 
      - 2024/like-father-like-daughter.md 
      - 2024/mourning-the-martyrdom.md 
      - 2024/boy-with-baguette.md 
      - 2024/untitled-1.md
      - 2022/arabic-breakfast-scene.md 
      - 2023/contemporary-syrian-face-covering.md 
      - 2023/nadia-and-lena.md 
      - 2022/pomegranate.md 
      - 2022/the-neo-orientalist.md 
      - 2024/the-scented-headpiece.md 
  curations:
    output: true
    permalink: /curation/:path
    order:
      - 2025/otherhalf.md
      - 2024/homeland.md
  google-earth:
    output: true
    permalink: /google-earth/:name
  google-earth-digital:
    output: true
    permalink: /google-earth/digital/:path
  about:
    output: true
    permalink: /about/:name
navigation:
  - text: "works"
    url: "/works"
  - text: "google earth"
    url: "/404"
    subpages:
      - text: "digital"
        url: "/google-earth/digital"
      - text: "physical"
        url: "/google-earth/physical"
      - text: "exploration"
        url: "/google-earth/exploration"
      - text: "essays"
        url: "/google-earth/essays"
      - text: "map"
        url: "https://maps.munaalfadl.com"
  - text: "curation"
    url: "/curation"
  - text: "about"
    url: "/404"
    subpages:
      - text: "statement"
        url: "/about/statement"
      - text: "exhibitions"
        url: "/about/exhibitions"
      - text: "contact"
        url: "/about/contact"